version: "3.9"
services:
  postgres:
    image: "postgres"
    environment: 
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  pgadmin:
    image: "dpage/pgadmin4"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@example.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "80:80"